### ISSUE TITLE
Incorrect DG link

### ISSUE THREAD

**Issue by damithc** [AY1920S2-CS2113-T14-4/tp#62]
The DG link in https://ay1920s2-cs2113-t14-4.github.io/tp/ is incorrect.

**Comment by SibingWu** [comment]
> The DG link in https://ay1920s2-cs2113-t14-4.github.io/tp/ is incorrect.

is the link correct now?

**Comment by SibingWu** [comment]
> The DG link in https://ay1920s2-cs2113-t14-4.github.io/tp/ is incorrect.

The link is updated accordingly
